# frozen_string_literal: true

require 'securerandom'

module Rack
  class MiniProfiler
    class FileStore < AbstractStore

      # Sub-class thread so we have a named thread (useful for debugging in Thread.list).
      class CacheCleanupThread < Thread
      end

      class FileCache
        def initialize(path, prefix)
          @path = path
          @prefix = prefix
        end

        def [](key)
          begin
            data = ::File.open(path(key), "rb") { |f| f.read }
            # rubocop:disable Security/MarshalLoad
            Marshal.load data
            # rubocop:enable Security/MarshalLoad
          rescue
            nil
          end
        end

        def []=(key, val)
          ::File.open(path(key), "wb+") do |f|
            f.sync = true
            f.write Marshal.dump(val)
          end
        end

        private
        if Gem.win_platform?
          def path(key)
            @path.dup << "/" << @prefix << "_" << key.gsub(/:/, '_')
          end
        else
          def path(key)
            @path.dup << "/" << @prefix << "_" << key
          end
        end
      end

      EXPIRES_IN_SECONDS = 60 * 60 * 24

      def log_it_fs(msg, data = {})
        msg = msg.to_s.ljust(40)[0,40]
        data_s = data.present? ? " data: #{data.to_json}" : ""
        Rails.logger.error "==== MINI_PROFILER: #{msg}: #{data_s}"
      end

      def initialize(args = nil)
        args ||= {}
        @path = args[:path]
        @expires_in_seconds = args[:expires_in] || EXPIRES_IN_SECONDS
        raise ArgumentError.new :path unless @path
        unless ::File.exist?(@path)
          log_it_fs("FILE_STORE_CREATE_DIR")
          FileUtils.mkdir_p(@path)
        end

        @timer_struct_cache = FileCache.new(@path, "mp_timers")
        @timer_struct_lock  = Mutex.new
        @user_view_cache    = FileCache.new(@path, "mp_views")
        @user_view_lock     = Mutex.new

        @auth_token_cache    = FileCache.new(@path, "tokens")
        @auth_token_lock     = Mutex.new

        me = self
        t = CacheCleanupThread.new do
          interval = 10
          cleanup_cache_cycle = 3600
          cycle_count = 1

          begin
            until Thread.current[:should_exit] do
              # TODO: a sane retry count before bailing

              # We don't want to hit the filesystem every 10s to clean up the cache so we need to do a bit of
              # accounting to avoid sleeping that entire time.  We don't want to sleep for the entire period because
              # it means the thread will stay live in hot deployment scenarios, keeping a potentially large memory
              # graph from being garbage collected upon undeploy.
              if cycle_count * interval >= cleanup_cache_cycle
                cycle_count = 1
                me.cleanup_cache
              end

              sleep(interval)
              cycle_count += 1
            end
          rescue
            # don't crash the thread, we can clean up next time
          end
        end

        at_exit { t[:should_exit] = true }
      end

      # TODO: what data is stored in a `page_struct`.  what should we call it?  RackMiniProfilerPage?
      # page_struct.class
      #   => Rack::MiniProfiler::TimerStruct::Page
      # page_struct.methods - Object.new.methods
      #   => [:page_name, :duration_ms_in_sql, :name, :duration_ms, :attributes, :extra_json, :root, :attributes_to_serialize, :[], :[]=]
      # page_struct.duration_ms_in_sql
      #   => 117.72117222426459
      # (byebug) page_struct.attributes.keys
      #   => [:id, :name, :started, :started_at, :machine_name, :level, :user, :has_user_viewed, :client_timings, :duration_milliseconds, :has_trivial_timings, :has_all_trivial_timings, :trivial_duration_threshold_milliseconds, :head, :sql_count, :cached_sql_count, :duration_milliseconds_in_sql, :has_sql_timings, :has_duplicate_sql_timings, :executed_readers, :executed_scalars, :executed_non_queries, :custom_timing_names, :custom_timing_stats, :custom_fields, :has_flamegraph, :flamegraph, :request_method, :request_path, :root]
      # page_struct[:id] => "dw59v7cgga7w2ngyvh0u"
      # page_struct[:root] => ....all the stuff....
      # (byebug) page_struct[:user]
      #  => "480475048"

      # rack_mini_profiler_pages => id, mp_id (string, unique index), mp_user (string), viewed (boolean), data (Marshal.dump(page_struct))
      def save(page_struct)
        log_it_fs("FILE_STORE_PAGE_SAVE", page_struct_id: page_struct[:id])
        # RackMiniProfilerPage.create!(
        #   mp_id: page_struct[:id],
        #   mp_user: page_struct[:user],
        #   viewed: false,
        #   data: Marshal.dump(page_struct)
        # )
        @timer_struct_lock.synchronize {
          @timer_struct_cache[page_struct[:id]] = page_struct
        }
      end

      # TODO: is the `id` generated by the gem?  if so, might want to rename it to `mini_profiler_id`
      # RackMiniProfilerPage.find(id)
      def load(id)
        @timer_struct_lock.synchronize {
          log_it_fs("FILE_STORE_PAGE_LOAD", id:)
          @timer_struct_cache[id]
        }
      end

      # user_view_cache?  page.viewed = false ?
      def set_unviewed(user, id)
        @user_view_lock.synchronize {
          log_it_fs("FILE_STORE_PAGE_SET_UNVIEWED", id:)
          current = @user_view_cache[user]
          current = [] unless Array === current
          current << id
          @user_view_cache[user] = current.uniq
        }
      end

      # page.viewed = true ?
      def set_viewed(user, id)
        @user_view_lock.synchronize {
          log_it_fs("FILE_STORE_PAGE_SET_VIEWED", id:)
          @user_view_cache[user] ||= []
          current = @user_view_cache[user]
          current = [] unless Array === current
          current.delete(id)
          @user_view_cache[user] = current.uniq
        }
      end

      # Page.where(user_id:).update_all(viewed: false)
      def set_all_unviewed(user, ids)
        @user_view_lock.synchronize {
          log_it_fs("FILE_STORE_PAGE_SET_ALL_UNVIEWED", ids:)
          @user_view_cache[user] = ids.uniq
        }
      end

      # Page.where(user_id:).where(viewed: false).pluck(:page_id)
      def get_unviewed_ids(user)
        @user_view_lock.synchronize {
          log_it_fs("FILE_STORE_PAGE_GET_ALL_UNVIEWED")
          @user_view_cache[user]
        }
      end

      # RackMiniProfilerAuthToken.delete_all
      # NOTE: this is called in the tests (or it could be called if outside does Rack::MiniProfiler.config.storage_instance.flush_tokens)
      def flush_tokens
        @auth_token_lock.synchronize {
          log_it_fs("FILE_STORE_AUTH_TOKEN_FLUSH_ALL")
          @auth_token_cache[""] = nil
        }
      end

      # NOTE: these tokens are for the entire service, not a specific user
      # all wrapped in a transaction
      #   tokens = RackMiniProfilerAuthToken.where(user_id:).active.order(created_at: :desc).limit(2)
      #   if tokens.count == 2, return the tokens
      #   if tokens.count == 1, create a new token, then return both tokens
      #   if tokens.count == 0, create a new token, then return the token
      def allowed_tokens
        log_it_fs("FILE_STORE_AUTH_TOKENS")
        @auth_token_lock.synchronize {
          token1, token2, cycle_at = @auth_token_cache[""]

          unless cycle_at && (Float === cycle_at) && (cycle_at > Process.clock_gettime(Process::CLOCK_MONOTONIC))
            token2 = token1
            token1 = SecureRandom.hex
            cycle_at = Process.clock_gettime(Process::CLOCK_MONOTONIC) + Rack::MiniProfiler::AbstractStore::MAX_TOKEN_AGE
          end

          @auth_token_cache[""] = [token1, token2, cycle_at]

          val = [token1, token2].compact
          log_it_fs("FILE_STORE_AUTH_TOKENS", tokens: val)
          val
        }
      end

      def cleanup_cache
        files = Dir.entries(@path)
        @timer_struct_lock.synchronize {
          files.each do |f|
            f = @path + '/' + f
            ::File.delete f if ::File.basename(f) =~ (/^mp_timers/) && ((Time.now - ::File.mtime(f)) > @expires_in_seconds)
          end
        }
        @user_view_lock.synchronize {
          files.each do |f|
            f = @path + '/' + f
            ::File.delete f if ::File.basename(f) =~ (/^mp_views/) && ((Time.now - ::File.mtime(f)) > @expires_in_seconds)
          end
        }
      end

    end
  end
end
